DeleteTask:
  handler: src/infrastructure/lambda/tasks/delete-task.handler
  name: DeleteTask
  memorySize: 128
  timeout: 5
  environment:
    TASK_TABLE_NAME: ${self:custom.tableNames.tasks}
  events:
    - http:
        path: tasks/{taskId}
        method: DELETE
        cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:DeleteItem'
      Resource: !GetAtt TasksTable.Arn
