FindAllTasks:
  handler: src/infrastructure/lambda/tasks/find-all-tasks.handler
  name: FindAllTasks
  memorySize: 128
  timeout: 5
  environment:
    TASK_TABLE_NAME: ${self:custom.tableNames.tasks}
  events:
    - http:
        path: tasks
        method: GET
        cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:Scan'
      Resource: !GetAtt TasksTable.Arn
