FindTaskById:
  handler: src/infrastructure/lambda/tasks/find-task-by-id.handler
  name: FindTaskById
  memorySize: 128
  timeout: 5
  environment:
    TASK_TABLE_NAME: ${self:custom.tableNames.tasks}
  events:
    - http:
        path: tasks/{taskId}
        method: GET
        cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:GetItem'
      Resource: !GetAtt TasksTable.Arn
