MarkTaskAsCompleted:
  handler: src/infrastructure/lambda/tasks/mark-task-as-completed.handler
  name: MarkTaskAsCompleted
  memorySize: 128
  timeout: 5
  environment:
    TASK_TABLE_NAME: ${self:custom.tableNames.tasks}
  events:
    - http:
        path: tasks/complete/{taskId}
        method: PUT
        cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:UpdateItem'
      Resource: !GetAtt TasksTable.Arn
